VENDOR_CHOICES = ["코스온", "코스트코", "이마트", "홈플러스", "마켓컬리", "롯데"]

DB_NAME = "GP"

# 제품 테이블 컬럼 인덱스
COL_VENDOR = 0
COL_PRODUCT = 1
COL_DEADLINE = 2
COL_PKG = 3
COL_ORDER = 4
COL_FINAL_ORDER = 5
COL_DIFF = 6
COL_PREV_RES = 7
COL_PRODUCTION = 8
COL_PLAN = 9
COL_PLAN_KG = 10
COL_CUR_PROD = 11
COL_SHIPMENT_TIME = 12
COL_TODAY_RES = 13
COL_TRATE = 14
COL_WORK_STATUS = 15
