# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1506, 847)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dirtyframe2 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dirtyframe2.sizePolicy().hasHeightForWidth())
        self.dirtyframe2.setSizePolicy(sizePolicy)
        self.dirtyframe2.setMinimumSize(QtCore.QSize(0, 0))
        self.dirtyframe2.setMaximumSize(QtCore.QSize(16777215, 64))
        self.dirtyframe2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dirtyframe2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dirtyframe2.setObjectName("dirtyframe2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.dirtyframe2)
        self.horizontalLayout_2.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_2.setSpacing(24)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dateText = QtWidgets.QLabel(self.dirtyframe2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateText.sizePolicy().hasHeightForWidth())
        self.dateText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(40)
        self.dateText.setFont(font)
        self.dateText.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.dateText.setIndent(-1)
        self.dateText.setObjectName("dateText")
        self.horizontalLayout_2.addWidget(self.dateText)
        self.frame_5 = QtWidgets.QFrame(self.dirtyframe2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_retailer = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_retailer.sizePolicy().hasHeightForWidth())
        self.label_retailer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(40)
        self.label_retailer.setFont(font)
        self.label_retailer.setLineWidth(1)
        self.label_retailer.setScaledContents(False)
        self.label_retailer.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_retailer.setIndent(-1)
        self.label_retailer.setObjectName("label_retailer")
        self.horizontalLayout_7.addWidget(self.label_retailer)
        self.btn_view = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_view.sizePolicy().hasHeightForWidth())
        self.btn_view.setSizePolicy(sizePolicy)
        self.btn_view.setMinimumSize(QtCore.QSize(120, 0))
        self.btn_view.setMaximumSize(QtCore.QSize(240, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(18)
        self.btn_view.setFont(font)
        self.btn_view.setObjectName("btn_view")
        self.horizontalLayout_7.addWidget(self.btn_view)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.verticalLayout_2.addWidget(self.dirtyframe2)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab1.sizePolicy().hasHeightForWidth())
        self.tab1.setSizePolicy(sizePolicy)
        self.tab1.setObjectName("tab1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget1 = QtWidgets.QTableWidget(self.tab1)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tableWidget1.setFont(font)
        self.tableWidget1.setObjectName("tableWidget1")
        self.tableWidget1.setColumnCount(0)
        self.tableWidget1.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget1)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab2.sizePolicy().hasHeightForWidth())
        self.tab2.setSizePolicy(sizePolicy)
        self.tab2.setObjectName("tab2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget2 = QtWidgets.QTableWidget(self.tab2)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tableWidget2.setFont(font)
        self.tableWidget2.setObjectName("tableWidget2")
        self.tableWidget2.setColumnCount(0)
        self.tableWidget2.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget2)
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget3 = QtWidgets.QTableWidget(self.tab3)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tableWidget3.setFont(font)
        self.tableWidget3.setObjectName("tableWidget3")
        self.tableWidget3.setColumnCount(0)
        self.tableWidget3.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget3)
        self.tabWidget.addTab(self.tab3, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidget4 = QtWidgets.QTableWidget(self.tab4)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tableWidget4.setFont(font)
        self.tableWidget4.setObjectName("tableWidget4")
        self.tableWidget4.setColumnCount(0)
        self.tableWidget4.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tableWidget4)
        self.tabWidget.addTab(self.tab4, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.view_frame2 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_frame2.sizePolicy().hasHeightForWidth())
        self.view_frame2.setSizePolicy(sizePolicy)
        self.view_frame2.setMinimumSize(QtCore.QSize(0, 100))
        self.view_frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.view_frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.view_frame2.setObjectName("view_frame2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.view_frame2)
        self.horizontalLayout_5.setContentsMargins(8, 4, 8, 4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.view_frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(60, 0))
        self.label_2.setMaximumSize(QtCore.QSize(32, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.dateEdit = QtWidgets.QDateEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(14)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_4.addWidget(self.dateEdit)
        self.verticalLayout.addWidget(self.frame_4)
        self.btn_admin = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(14)
        self.btn_admin.setFont(font)
        self.btn_admin.setStyleSheet("QPushButton {\n"
"    background-color: #EEEEEE;\n"
"    border: 1px solid #CCCCCC;\n"
"    color: #AAAAAA;\n"
"}")
        self.btn_admin.setObjectName("btn_admin")
        self.verticalLayout.addWidget(self.btn_admin)
        self.horizontalLayout_5.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.view_frame2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_prev = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_prev.sizePolicy().hasHeightForWidth())
        self.btn_prev.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_prev.setFont(font)
        self.btn_prev.setObjectName("btn_prev")
        self.horizontalLayout.addWidget(self.btn_prev)
        self.btn_next = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_next.sizePolicy().hasHeightForWidth())
        self.btn_next.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_next.setFont(font)
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout.addWidget(self.btn_next)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.btn_costco = QtWidgets.QPushButton(self.view_frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_costco.sizePolicy().hasHeightForWidth())
        self.btn_costco.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_costco.setFont(font)
        self.btn_costco.setStyleSheet("QPushButton {\n"
"    background-color: #d7e9f8;\n"
"    border: 1px solid #9fbad2;\n"
"    padding: 6px 12px;\n"
"    border-radius: 6px;\n"
"    color: #1f2d3d;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c9ddf3;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #bcd2ea;\n"
"}")
        self.btn_costco.setObjectName("btn_costco")
        self.horizontalLayout_5.addWidget(self.btn_costco)
        self.btn_emart = QtWidgets.QPushButton(self.view_frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_emart.sizePolicy().hasHeightForWidth())
        self.btn_emart.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_emart.setFont(font)
        self.btn_emart.setStyleSheet("QPushButton {\n"
"    background-color: #e8e1f3;\n"
"    border: 1px solid #b6a8d1;\n"
"    padding: 6px 12px;\n"
"    border-radius: 6px;\n"
"    color: #2b2a35;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #ddd4ee;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #d2c9e8;\n"
"}\n"
"")
        self.btn_emart.setObjectName("btn_emart")
        self.horizontalLayout_5.addWidget(self.btn_emart)
        self.btn_homeplus = QtWidgets.QPushButton(self.view_frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_homeplus.sizePolicy().hasHeightForWidth())
        self.btn_homeplus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_homeplus.setFont(font)
        self.btn_homeplus.setStyleSheet("QPushButton {\n"
"    background-color: #e9e3da;\n"
"    border: 1px solid #bfb7ac;\n"
"    padding: 6px 12px;\n"
"    border-radius: 6px;\n"
"    color: #2b2a28;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #ded7cd;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #d3ccc2;\n"
"}\n"
"")
        self.btn_homeplus.setObjectName("btn_homeplus")
        self.horizontalLayout_5.addWidget(self.btn_homeplus)
        self.btn_kurly = QtWidgets.QPushButton(self.view_frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_kurly.sizePolicy().hasHeightForWidth())
        self.btn_kurly.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_kurly.setFont(font)
        self.btn_kurly.setStyleSheet("QPushButton {\n"
"    background-color: #d9f1e7;\n"
"    border: 1px solid #94c5ad;\n"
"    padding: 6px 12px;\n"
"    border-radius: 6px;\n"
"    color: #1f2d3d;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #cbe8dc;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #c0dfd3;\n"
"}")
        self.btn_kurly.setObjectName("btn_kurly")
        self.horizontalLayout_5.addWidget(self.btn_kurly)
        self.verticalLayout_2.addWidget(self.view_frame2)
        self.view_frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_frame.sizePolicy().hasHeightForWidth())
        self.view_frame.setSizePolicy(sizePolicy)
        self.view_frame.setMinimumSize(QtCore.QSize(0, 100))
        self.view_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.view_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.view_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.view_frame.setObjectName("view_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.view_frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_6 = QtWidgets.QFrame(self.view_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(80, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.tab_frequency = QtWidgets.QLineEdit(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_frequency.sizePolicy().hasHeightForWidth())
        self.tab_frequency.setSizePolicy(sizePolicy)
        self.tab_frequency.setMinimumSize(QtCore.QSize(0, 32))
        self.tab_frequency.setMaximumSize(QtCore.QSize(120, 16777215))
        self.tab_frequency.setObjectName("tab_frequency")
        self.verticalLayout_7.addWidget(self.tab_frequency)
        self.horizontalLayout_8.addWidget(self.frame_7)
        self.btn_autoPage = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_autoPage.sizePolicy().hasHeightForWidth())
        self.btn_autoPage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_autoPage.setFont(font)
        self.btn_autoPage.setObjectName("btn_autoPage")
        self.horizontalLayout_8.addWidget(self.btn_autoPage)
        self.horizontalLayout_6.addWidget(self.frame_6)
        self.frame_3 = QtWidgets.QFrame(self.view_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btn_show_hide = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_show_hide.sizePolicy().hasHeightForWidth())
        self.btn_show_hide.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_show_hide.setFont(font)
        self.btn_show_hide.setStyleSheet("QPushButton {\n"
"    background-color: #fff0d6;\n"
"    border: 1px solid #94c5ad;\n"
"    padding: 6px 12px;\n"
"    border-radius: 6px;\n"
"    color: #1f2d3d;\n"
"}")
        self.btn_show_hide.setObjectName("btn_show_hide")
        self.horizontalLayout_9.addWidget(self.btn_show_hide)
        self.btn_hide_row = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_hide_row.sizePolicy().hasHeightForWidth())
        self.btn_hide_row.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_hide_row.setFont(font)
        self.btn_hide_row.setStyleSheet("QPushButton {\n"
"    background-color: #fff0d6;\n"
"    border: 1px solid #94c5ad;\n"
"    padding: 6px 12px;\n"
"    border-radius: 6px;\n"
"    color: #1f2d3d;\n"
"}")
        self.btn_hide_row.setObjectName("btn_hide_row")
        self.horizontalLayout_9.addWidget(self.btn_hide_row)
        self.horizontalLayout_6.addWidget(self.frame_3)
        self.btn_product = QtWidgets.QPushButton(self.view_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_product.sizePolicy().hasHeightForWidth())
        self.btn_product.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_product.setFont(font)
        self.btn_product.setStyleSheet("QPushButton {\n"
"    background-color: #d7e9f8;\n"
"    border: 1px solid #9fbad2;\n"
"    padding: 6px 12px;\n"
"    border-radius: 6px;\n"
"    color: #1f2d3d;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c9ddf3;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #bcd2ea;\n"
"}")
        self.btn_product.setObjectName("btn_product")
        self.horizontalLayout_6.addWidget(self.btn_product)
        self.btn_raw = QtWidgets.QPushButton(self.view_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_raw.sizePolicy().hasHeightForWidth())
        self.btn_raw.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_raw.setFont(font)
        self.btn_raw.setStyleSheet("QPushButton {\n"
"    background-color: #e8e1f3;\n"
"    border: 1px solid #b6a8d1;\n"
"    padding: 6px 12px;\n"
"    border-radius: 6px;\n"
"    color: #2b2a35;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #ddd4ee;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #d2c9e8;\n"
"}\n"
"")
        self.btn_raw.setObjectName("btn_raw")
        self.horizontalLayout_6.addWidget(self.btn_raw)
        self.btn_sauce = QtWidgets.QPushButton(self.view_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sauce.sizePolicy().hasHeightForWidth())
        self.btn_sauce.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_sauce.setFont(font)
        self.btn_sauce.setStyleSheet("QPushButton {\n"
"    background-color: #e9e3da;\n"
"    border: 1px solid #bfb7ac;\n"
"    padding: 6px 12px;\n"
"    border-radius: 6px;\n"
"    color: #2b2a28;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #ded7cd;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #d3ccc2;\n"
"}\n"
"")
        self.btn_sauce.setObjectName("btn_sauce")
        self.horizontalLayout_6.addWidget(self.btn_sauce)
        self.btn_vege = QtWidgets.QPushButton(self.view_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_vege.sizePolicy().hasHeightForWidth())
        self.btn_vege.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_vege.setFont(font)
        self.btn_vege.setStyleSheet("QPushButton {\n"
"    background-color: #d9f1e7;\n"
"    border: 1px solid #94c5ad;\n"
"    padding: 6px 12px;\n"
"    border-radius: 6px;\n"
"    color: #1f2d3d;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #cbe8dc;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #c0dfd3;\n"
"}")
        self.btn_vege.setObjectName("btn_vege")
        self.horizontalLayout_6.addWidget(self.btn_vege)
        self.verticalLayout_2.addWidget(self.view_frame)
        self.control_frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_frame.sizePolicy().hasHeightForWidth())
        self.control_frame.setSizePolicy(sizePolicy)
        self.control_frame.setMinimumSize(QtCore.QSize(0, 100))
        self.control_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.control_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.control_frame.setObjectName("control_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.control_frame)
        self.horizontalLayout_3.setContentsMargins(8, 4, 8, 4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_complete = QtWidgets.QPushButton(self.control_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_complete.sizePolicy().hasHeightForWidth())
        self.btn_complete.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_complete.setFont(font)
        self.btn_complete.setStyleSheet("QPushButton {\n"
"    background-color: #d7e9f8;\n"
"    border: 1px solid #9fbad2;\n"
"    padding: 6px 12px;\n"
"    border-radius: 6px;\n"
"    color: #1f2d3d;\n"
"}")
        self.btn_complete.setObjectName("btn_complete")
        self.horizontalLayout_3.addWidget(self.btn_complete)
        self.btn_add = QtWidgets.QPushButton(self.control_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add.sizePolicy().hasHeightForWidth())
        self.btn_add.setSizePolicy(sizePolicy)
        self.btn_add.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_add.setFont(font)
        self.btn_add.setStyleSheet("QPushButton {\n"
"    background-color: #e9e3da;\n"
"    border: 1px solid #bfb7ac;\n"
"    padding: 6px 12px;\n"
"    border-radius: 6px;\n"
"    color: #2b2a28;\n"
"}")
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout_3.addWidget(self.btn_add)
        self.btn_del = QtWidgets.QPushButton(self.control_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_del.sizePolicy().hasHeightForWidth())
        self.btn_del.setSizePolicy(sizePolicy)
        self.btn_del.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_del.setFont(font)
        self.btn_del.setStyleSheet("QPushButton {\n"
"    background-color: #e9e3da;\n"
"    border: 1px solid #bfb7ac;\n"
"    padding: 6px 12px;\n"
"    border-radius: 6px;\n"
"    color: #2b2a28;\n"
"}")
        self.btn_del.setObjectName("btn_del")
        self.horizontalLayout_3.addWidget(self.btn_del)
        self.btn_del_row = QtWidgets.QPushButton(self.control_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_del_row.sizePolicy().hasHeightForWidth())
        self.btn_del_row.setSizePolicy(sizePolicy)
        self.btn_del_row.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_del_row.setFont(font)
        self.btn_del_row.setStyleSheet("QPushButton {\n"
"    background-color: #e9e3da;\n"
"    border: 1px solid #bfb7ac;\n"
"    padding: 6px 12px;\n"
"    border-radius: 6px;\n"
"    color: #2b2a28;\n"
"}")
        self.btn_del_row.setObjectName("btn_del_row")
        self.horizontalLayout_3.addWidget(self.btn_del_row)
        self.btn_update = QtWidgets.QPushButton(self.control_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_update.sizePolicy().hasHeightForWidth())
        self.btn_update.setSizePolicy(sizePolicy)
        self.btn_update.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_update.setFont(font)
        self.btn_update.setStyleSheet("QPushButton {\n"
"    background-color: #d9f1e7;\n"
"    border: 1px solid #94c5ad;\n"
"    padding: 6px 12px;\n"
"    border-radius: 6px;\n"
"    color: #1f2d3d;\n"
"}")
        self.btn_update.setObjectName("btn_update")
        self.horizontalLayout_3.addWidget(self.btn_update)
        self.btn_update_product = QtWidgets.QPushButton(self.control_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_update_product.sizePolicy().hasHeightForWidth())
        self.btn_update_product.setSizePolicy(sizePolicy)
        self.btn_update_product.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_update_product.setFont(font)
        self.btn_update_product.setStyleSheet("QPushButton {\n"
"    background-color: #d9f1e7;\n"
"    border: 1px solid #94c5ad;\n"
"    padding: 6px 12px;\n"
"    border-radius: 6px;\n"
"    color: #1f2d3d;\n"
"}")
        self.btn_update_product.setObjectName("btn_update_product")
        self.horizontalLayout_3.addWidget(self.btn_update_product)
        self.btn_excel = QtWidgets.QPushButton(self.control_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_excel.sizePolicy().hasHeightForWidth())
        self.btn_excel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_excel.setFont(font)
        self.btn_excel.setObjectName("btn_excel")
        self.horizontalLayout_3.addWidget(self.btn_excel)
        self.btn_log = QtWidgets.QPushButton(self.control_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_log.sizePolicy().hasHeightForWidth())
        self.btn_log.setSizePolicy(sizePolicy)
        self.btn_log.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_log.setFont(font)
        self.btn_log.setObjectName("btn_log")
        self.horizontalLayout_3.addWidget(self.btn_log)
        self.btn_custom = QtWidgets.QPushButton(self.control_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_custom.sizePolicy().hasHeightForWidth())
        self.btn_custom.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR Medium")
        font.setPointSize(16)
        self.btn_custom.setFont(font)
        self.btn_custom.setStyleSheet("QPushButton {\n"
"    background-color: #e8e1f3;\n"
"    border: 1px solid #b6a8d1;\n"
"    padding: 6px 12px;\n"
"    border-radius: 6px;\n"
"    color: #2b2a35;\n"
"}")
        self.btn_custom.setObjectName("btn_custom")
        self.horizontalLayout_3.addWidget(self.btn_custom)
        self.verticalLayout_2.addWidget(self.control_frame)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.dateText.setText(_translate("Form", "2025-11-24"))
        self.label_retailer.setText(_translate("Form", "코스트코"))
        self.btn_view.setText(_translate("Form", "전체화면"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("Form", "제품"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("Form", "원료"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("Form", "소스"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab4), _translate("Form", "야채"))
        self.label_2.setText(_translate("Form", "생산일"))
        self.btn_admin.setText(_translate("Form", "관리자"))
        self.btn_prev.setText(_translate("Form", "이전일"))
        self.btn_next.setText(_translate("Form", "다음일"))
        self.btn_costco.setText(_translate("Form", "코스트코"))
        self.btn_emart.setText(_translate("Form", "이마트"))
        self.btn_homeplus.setText(_translate("Form", "홈플러스"))
        self.btn_kurly.setText(_translate("Form", "마켓컬리"))
        self.label_3.setText(_translate("Form", "화면전환 주기"))
        self.btn_autoPage.setText(_translate("Form", "화면고정"))
        self.btn_show_hide.setText(_translate("Form", "숨김제외"))
        self.btn_hide_row.setText(_translate("Form", "행 숨김"))
        self.btn_product.setText(_translate("Form", "제품"))
        self.btn_raw.setText(_translate("Form", "원료"))
        self.btn_sauce.setText(_translate("Form", "소스"))
        self.btn_vege.setText(_translate("Form", "야채"))
        self.btn_complete.setText(_translate("Form", "작업완료"))
        self.btn_add.setText(_translate("Form", "표 생성"))
        self.btn_del.setText(_translate("Form", "표 삭제"))
        self.btn_del_row.setText(_translate("Form", "행 삭제"))
        self.btn_update.setText(_translate("Form", "발주량 갱신"))
        self.btn_update_product.setText(_translate("Form", "출고량 갱신"))
        self.btn_excel.setText(_translate("Form", "엑셀"))
        self.btn_log.setText(_translate("Form", "로그"))
        self.btn_custom.setText(_translate("Form", "품명 관리"))
